# Generated by Django 2.1.9 on 2020-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerData',
            fields=[
                ('Org_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Org_Name', models.CharField(max_length=100)),
                ('Org_Ins', models.CharField(default='None', max_length=200)),
                ('Org_Email', models.CharField(max_length=80)),
                ('Org_Password', models.CharField(max_length=20)),
                ('Status', models.CharField(default='Active', max_length=10)),
            ],
            options={
                'db_table': 'OrganizerData',
            },
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
