# Generated by Django 2.2.3 on 2020-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200925_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerdata',
            name='Org_Email',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='organizerdata',
            name='Status',
            field=models.CharField(default='Deactive', max_length=10),
        ),
    ]
