# Generated by Django 3.1.1 on 2020-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201007_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('Quiz_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Org_ID', models.CharField(max_length=20)),
                ('Quiz_Name', models.CharField(max_length=100)),
                ('Quiz_Category', models.CharField(max_length=50)),
                ('Question_Count', models.CharField(max_length=5)),
                ('Marks_Per_Ques', models.CharField(max_length=5)),
                ('Status', models.CharField(default='Deactive', max_length=10)),
            ],
            options={
                'db_table': 'QuizData',
            },
        ),
    ]
