# Generated by Django 3.1.1 on 2020-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_quizdata_maximum_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('Question_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Quiz_ID', models.CharField(max_length=20)),
                ('Question', models.CharField(max_length=1000)),
                ('Option_A', models.CharField(max_length=100)),
                ('Option_B', models.CharField(max_length=100)),
                ('Option_C', models.CharField(max_length=100)),
                ('Option_D', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'QuestionData',
            },
        ),
    ]
