# Generated by Django 3.1.2 on 2020-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_questiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('Candidate_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Quiz_ID', models.CharField(max_length=20)),
                ('Candidate_Name', models.CharField(max_length=100)),
                ('Candidate_Email', models.CharField(max_length=100)),
                ('Candidate_Course', models.CharField(max_length=100)),
                ('Candidate_Branch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CandidateData',
            },
        ),
    ]
