# Generated by Django 3.1.2 on 2020-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_candidatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='Quiz_Password',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
