# Generated by Django 3.1.2 on 2020-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_quizdata_quiz_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedata',
            name='Status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
