# Generated by Django 3.1.2 on 2020-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_candidatedata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_ID', models.CharField(max_length=20)),
                ('Quiz_ID', models.CharField(max_length=20)),
                ('Result', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ResultData',
            },
        ),
    ]
